---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: home
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.13.7
   syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
