apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: s3-backup
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "15"  
spec:
  cron: "* * * * *"
  task: "snapshot"
  groups:
  - default
  retain: 4
  concurrency: 2
