---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: daily-s3-backup
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  cron: "0 1 * * *"
  task: "backup"
  groups:
  - default
  retain: 4
  concurrency: 2
