#apiVersion: v1
#kind: Namespace
#metadata:
#  name: ingress-nginx
#  annotations:
#    argocd.argoproj.io/sync-wave: "-10"  

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: home
  syncPolicy:
   automated:
     prune: true
     selfHeal: true
   syncOptions:
   - CreateNamespace=true
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.4.0
    helm:
      version: v3
      values: |-
        controller:
          service:
            externalIPs:
              - 192.168.2.202
