# https://github.com/influxdata/helm-charts/tree/master/charts/influxdb2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: home
  syncPolicy: {}
  source:
    chart: influxdb2
    repoURL: https://helm.influxdata.com
    targetRevision: 2.1.1
    helm:
      version: v3
      values: |-
          image:
            repository: influxdb
            tag: "2.2.0"
          service:
            type: LoadBalancer
            loadBalancerIP: 192.168.2.204
          persistence:
            enabled: true
            accessMode: ReadWriteOnce
            size: 30Gi
            mountPath: /var/lib/influxdb2
            subPath: ""
            useExisting: false
            name: