apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-home-rg
  namespace: metallb-system
spec:
  addresses:
  - 192.168.2.200-192.168.2.245

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pool-home-rg
  namespace: metallb-system
