---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    namespace: ingress
    server: https://kubernetes.default.svc
  project: core-services-unrestricted
  syncPolicy: {}
  source:
    chart: metallb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 4.1.14
