apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "-10"  

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: metallb-system
spec:
  destination:
    namespace: ingress
    server: https://kubernetes.default.svc
  project: core-services-unrestricted
  syncPolicy: {}
  source:
    chart: metallb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 4.1.14
