#https://github.com/grafana/helm-charts/tree/main/charts/grafana
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: home
  syncPolicy:
   automated:
     prune: true
     selfHeal: true
   syncOptions:
    - Replace=true
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.50.7
    helm:
      version: v3
      values: |-
          service:
            enabled: true
            type: ClusterIP
            port: 80
            targetPort: 3000
            annotations: {}
            labels: {}
            portName: service
            appProtocol: ""
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              # kubernetes.io/tls-acme: "true"
            labels: {}
            path: /
            pathType: Prefix
            hosts:
              - grafana.home
          persistence:
            type: pvc
            enabled: true
            # storageClassName: default
            accessModes:
              - ReadWriteOnce
            size: 10Gi
            # annotations: {}
            finalizers:
              - kubernetes.io/pvc-protection
            # selectorLabels: {}
            ## Sub-directory of the PV to mount. Can be templated.
            # subPath: ""
            ## Name of an existing PVC. Can be templated.
            # existingClaim:
            ## Extra labels to apply to a PVC.
            extraPvcLabels: {}
            inMemory:
              enabled: false
